### ISSUE TITLE
Handling elisions and apostrophes

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [PonteIneptique/boudams#12]
At least for French, the corpus processor should delete the apostrophes (', ʼ, ’) from the training input lines, and there should perhaps be a specific class in the mask for word boundary with elision.

I'll try to look into it.

**Comment by PonteIneptique** [comment]
Rather than adding a class, I would probably handle them before and after boudams (removing them and reinserting them) just like I do for Pie.

**Comment by Jean-Baptiste-Camps** [comment]
Ok, I have made some changes that should solve the issue in #13 .
