### ISSUE TITLE
Manage large dataset

### ISSUE THREAD

**Issue by volodos621** [PonteIneptique/boudams#16]
Hi!

Everything works with a small dataset (total 4.000 lines with few characters divided in train, test and dev), but I get some errors when trying with larger dataset (> 30.000 lines and chars > 1000 for some lines), even if I change "max_sentence_size" in my .json file.

```
File "/home/volos/boudams/env/lib/python3.7/site-packages/boudams-0.1.2-py3.7.egg/boudams/encoder.py", line 237, in readunit
ValueError: too many values to unpack (expected 2)

```
I was wondering if my files were well made, so I have tried to generate the train, dev and test files with a lorem ipsum text (just for a quick test):
`boudams dataset generate datasets/lorem/ corpus.txt --max_char_length 250`
but I get the following output with nothing in the generated files:

```
[DONE] Files available at datasets/lorem/ 
------
REPORT
File : test.tsv
Max char : 0
Min char : 250
Max words: 0
Min words: 250
------
------
REPORT
File : dev.tsv
Max char : 0
Min char : 250
Max words: 0
Min words: 250
------
------
REPORT
File : train.tsv
Max char : 0
Min char : 250
Max words: 0
Min words: 250
```

So my question is: is-there a way to manage large dataset (high number of lines with a lot of chars by lines)? I guess I miss something somewhere... Thanks!

**Comment by PonteIneptique** [comment]
Can you upload some part of it ? Just so I can check :) Including your lorem :)

**Comment by PonteIneptique** [comment]
```
File "/home/volos/boudams/env/lib/python3.7/site-packages/boudams-0.1.2-py3.7.egg/boudams/encoder.py", line 237, in readunit
ValueError: too many values to unpack (expected 2)
```
Also, I think you should check you have not more than one `tab` per line. This is probably the issue:

https://github.com/PonteIneptique/boudams/blob/b9fbb8e42d6893e04447ab69b275e01af03669f8/boudams/encoder.py#L237

**Comment by volodos621** [comment]
> Also, I think you should check you have not more than one tab per line. This is probably the issue:

You are right, thanks, I don't know from where it comes! It works now. I keep you in touch about results.

And the lorem : [corpus.txt](https://github.com/PonteIneptique/boudams/files/4804127/corpus.txt)
