### ISSUE TITLE
CPU Memory leaks

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [PonteIneptique/boudams#20]
I'm currently training on a large dataset (PL), with 17377805 training examples. 
Training on cuda 10.2, and whatever the batch size, I observe that, as training iteration goes, CPU (not GPU) memory starts to fill up, until it occupies 100% RAM and 100% SWAP.

I wonder if it could be related to: 
https://github.com/pytorch/pytorch/issues/13246

Same behaviour on, at least, PyTorch 1.6 to 1.8.1.

**Comment by PonteIneptique** [comment]
@Jean-Baptiste-Camps can you try the current lightning branch for this issue ? Or share the dataset ? :)

**Comment by Jean-Baptiste-Camps** [comment]
And we're done with that !
